  NETLIFY_BLOBS_ENABLED = "true"
[dev]
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["./**/*"]

  [functions.environment]
    NETLIFY_BLOBS_ENABLED = "true"
